# Generated by Django 5.1.7 on 2025-03-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wordgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagramhunt.anagramhunt')),
            ],
        ),
    ]
