# Generated by Django 5.1.7 on 2025-03-25 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0003_wordscore_delete_playerscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscore',
            name='wordlength',
            field=models.CharField(default=5, max_length=8, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
