# Generated by Django 5.1.7 on 2025-03-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0004_wordscore_wordlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordscore',
            name='wordgame',
        ),
        migrations.RemoveField(
            model_name='wordscore',
            name='wordlength',
        ),
        migrations.AddField(
            model_name='wordscore',
            name='wordlengths',
            field=models.CharField(choices=[('5', '5 length'), ('6', '6 length'), ('7', '7 length'), ('8', '8 length')], default='5', max_length=1),
        ),
    ]
