# Generated by Django 5.1.7 on 2025-03-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0005_remove_wordscore_wordgame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscore',
            name='score',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
