# Generated by Django 5.1.7 on 2025-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0008_alter_wordscore_wordlengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordscore',
            name='wordlengths',
            field=models.CharField(choices=[('5', '5 length'), ('6', '6 length'), ('7', '7 length'), ('8', '8 length')]),
        ),
    ]
