# Generated by Django 5.1.7 on 2025-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0010_alter_wordscore_wordlengths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordscore',
            name='wordlengths',
        ),
        migrations.AddField(
            model_name='wordscore',
            name='word_lengths',
            field=models.CharField(choices=[('5', '5 letters'), ('6', '6 letters'), ('7', '7 letters'), ('8', '8 letters')], default='5', max_length=1),
        ),
        migrations.AlterField(
            model_name='anagramhunt',
            name='play',
            field=models.CharField(max_length=100),
        ),
    ]
