# Generated by Django 5.1.7 on 2025-03-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0011_remove_wordscore_wordlengths_wordscore_word_lengths_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordscore',
            old_name='word_lengths',
            new_name='word_length',
        ),
    ]
