# Generated by Django 5.1.7 on 2025-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagramhunt', '0012_rename_word_lengths_wordscore_word_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscore',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
