# Generated by Django 5.1.7 on 2025-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0003_mathscore_delete_playerscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathscore',
            name='levellength',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
