# Generated by Django 5.1.7 on 2025-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0004_mathscore_levellength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathscore',
            old_name='levellength',
            new_name='highest_number',
        ),
        migrations.AlterField(
            model_name='mathfacts',
            name='play',
            field=models.CharField(max_length=100),
        ),
    ]
