# Generated by Django 5.1.7 on 2025-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0005_rename_levellength_mathscore_highest_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathscore',
            name='mathgame',
        ),
        migrations.AddField(
            model_name='mathscore',
            name='chosen_operation',
            field=models.CharField(choices=[('1', 'Addition'), ('2', 'Subtraction'), ('3', 'Multiplication'), ('4', 'Division')], default='Addition'),
        ),
    ]
