# Generated by Django 5.1.7 on 2025-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0006_remove_mathscore_mathgame_mathscore_chosen_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathscore',
            name='score',
            field=models.IntegerField(default=1, verbose_name=100),
            preserve_default=False,
        ),
    ]
