# Generated by Django 5.1.7 on 2025-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0007_mathscore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathscore',
            old_name='highest_number',
            new_name='chosen_highest_number',
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='chosen_operation',
            field=models.CharField(choices=[('1', 'Addition'), ('2', 'Subtraction'), ('3', 'Multiplication'), ('4', 'Division')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='mathscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
