# Generated by Django 5.1.7 on 2025-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0008_rename_highest_number_mathscore_chosen_highest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathscore',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
