# Generated by Django 5.1.7 on 2025-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathfacts', '0011_alter_mathscore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
